In [1]:
from numpy.random import seed
import pandas as pd
import numpy as np
from sklearn.preprocessing import minmax_scale
# from keras_diagram import ascii
from keras.layers.convolutional import Conv2D, MaxPooling2D, Conv1D, MaxPooling1D
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
import keras

data = pd.read_csv("creditcard.csv")

# Normalise and reshape the Amount column, so it's values lie between -1 and 1
from sklearn.preprocessing import StandardScaler
data['norm_Amount'] = StandardScaler().fit_transform(data['Amount'].reshape(-1,1))

# Drop the old Amount column and also the Time column as we don't want to include this at this stage
data = data.drop(['Amount'], axis=1)

data.sort_values(['Time'])


Using TensorFlow backend.
/Users/HarryG1/Documents/University/Year_3/DeepLearning-CreditCardFraud/devEnv/lib/python2.7/site-packages/ipykernel_launcher.py:18: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
5            2.0  -0.425966   0.960523  1.141109 -0.168252  0.420987   
6            4.0   1.229658   0.141004  0.045371  1.202613  0.191881   
7            7.0  -0.644269   1.417964  1.074380 -0.492199  0.948934   
8            7.0  -0.894286   0.286157 -0.113192 -0.271526  2.669599   
9            9.0  -0.338262   1.119593  1.044367 -0.222187  0.499361   
10          10.0   1.449044  -1.176339  0.913860 -1.375667 -1.971383   
11          10.0   0.384978   0.616109 -0.874300 -0.094019  2.924584   
12          10.0   1.249999  -1.221637  0.383930 -1.234899 -1.485419   
13          11.0   1.069374   0.287722  0.828613  2.712520 -0.178398   
15          12.0  -0.752417   0.345485  2.057323 -1.468643 -1.158394   
16          12.0   1.103215  -0.040296  1.267332  1.289091 -0.735997   
14          12.0  -2.791855  -0.327771  1.641750  1.767473 -0.136588   
17          13.0  -0.436905   0.918966  0.924591 -0.727219  0.915679   
18          14.0  -5.401258  -5.450148  1.186305  1.736239  3.049106   
19          15.0   1.492936  -1.029346  0.454795 -1.438026 -1.555434   
20          16.0   0.694885  -1.361819  1.029221  0.834159 -1.191209   
21          17.0   0.962496   0.328461 -0.171479  2.109204  1.129566   
22          18.0   1.166616   0.502120 -0.067300  2.261569  0.428804   
23          18.0   0.247491   0.277666  1.185471 -0.092603 -1.314394   
24          22.0  -1.946525  -0.044901 -0.405570 -1.013057  2.941968   
25          22.0  -2.074295  -0.121482  1.322021  0.410008  0.295198   
26          23.0   1.173285   0.353498  0.283905  1.133563 -0.172577   
27          23.0   1.322707  -0.174041  0.434555  0.576038 -0.836758   
28          23.0  -0.414289   0.905437  1.727453  1.473471  0.007443   
29          23.0   1.059387  -0.175319  1.266130  1.186110 -0.786002   
...          ...        ...        ...       ...       ...       ...   
284777  172764.0   2.079137  -0.028723 -1.343392  0.358000 -0.045791   
284778  172764.0  -0.764523   0.588379 -0.907599 -0.418847  0.901528   
284780  172766.0  -1.727503   1.108356  2.219561  1.148583 -0.884199   
284781  172766.0  -1.139015  -0.155510  1.894478 -1.138957  1.451777   
284779  172766.0   1.975178  -0.616244 -2.628295 -0.406246  2.327804   
284782  172767.0  -0.268061   2.540315 -1.400915  4.846661  0.639105   
284783  172768.0  -1.796092   1.929178 -2.828417 -1.689844  2.199572   
284784  172768.0  -0.669662   0.923769 -1.543167 -1.560729  2.833960   
284785  172768.0   0.032887   0.545338 -1.185844 -1.729828  2.932315   
284786  172768.0  -2.076175   2.142238 -2.522704 -1.888063  1.982785   
284787  172769.0  -1.029719  -1.110670 -0.636179 -0.840816  2.424360   
284788  172770.0   2.007418  -0.280235 -0.208113  0.335261 -0.715798   
284789  172770.0  -0.446951   1.302212 -0.168583  0.981577  0.578957   
284790  172771.0  -0.515513   0.971950 -1.014580 -0.677037  0.912430   
284791  172774.0  -0.863506   0.874701  0.420358 -0.530365  0.356561   
284792  172774.0  -0.724123   1.485216 -1.132218 -0.607190  0.709499   
284793  172775.0   1.971002  -0.699067 -1.697541 -0.617643  1.718797   
284794  172777.0  -1.266580  -0.400461  0.956221 -0.723919  1.531993   
284795  172778.0 -12.516732  10.187818 -8.476671 -2.510473 -4.586669   
284796  172780.0   1.884849  -0.143540 -0.999943  1.506772 -0.035300   
284798  172782.0   0.219529   0.881246 -0.635891  0.960928 -0.152971   
284797  172782.0  -0.241923   0.712247  0.399806 -0.463406  0.244531   
284799  172783.0  -1.775135  -0.004235  1.189786  0.331096  1.196063   
284800  172784.0   2.039560  -0.175233 -1.196825  0.

In [2]:
# Assign variables x and y corresponding to row data and it's class value
X = data.ix[:, data.columns != 'Class']
y = data.ix[:, data.columns == 'Class']

def generate_train_test_sample(x_data, y_data): 
    ''' 1) Generate new, random train-test split
        2) Random smote oversample the train data, keeping test data unseen
        3) Use this new train-test split to fit and test model
    '''

    X_train, X_test, y_train, y_test = train_test_split(x_data,y_data,test_size = 0.3)

    from collections import Counter
    from imblearn.over_sampling import SMOTE
    sm = SMOTE()
    X_res, y_res = sm.fit_sample(X_train, y_train)
    print('Resampling the data with SMOTE. . .')
    print('Resampled training dataset shape {}'.format(Counter(y_res)))

    return X_res, y_res, X_test, y_test

def generate_train_test_timeseries(data,cuttoff_percent=0.7):
    cutoff = math.floor(X.shape[0] *cuttoff_percent) 
    
    X_train = data.ix[0:cutoff, data.columns != 'Class']
    y_train = data.ix[0:cutoff, data.columns == 'Class']
    X_test = data.ix[cutoff:, data.columns != 'Class']
    y_test = data.ix[cutoff:, data.columns == 'Class']
    
    return X_train, y_train, X_test, y_test
    
########################################################################

# X_res, y_res, X_test, y_test = generate_train_test_sample(X, y)

# print X_res.shape, type(X_res)
# print y_res.shape

# X_train = X_res.reshape(X_res.shape[0], 29, 1)
# Y_train = y_res.reshape(y_res.shape[0], 1)
# X_test = X_test.values.reshape(X_test.values.shape[0], 29, 1)
# Y_test = y_test.values.reshape(y_test.values.shape[0], 1)

# Y_test = keras.utils.to_categorical(Y_test)
# Y_train = keras.utils.to_categorical(Y_train)
# print Y_test.shape
# print Y_train.shape




/Users/HarryG1/Documents/University/Year_3/DeepLearning-CreditCardFraud/devEnv/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [3]:
data[data['Class']==1]

Time        V1        V2         V3        V4        V5        V6  \
541        406.0 -2.312227  1.951992  -1.609851  3.997906 -0.522188 -1.426545   
623        472.0 -3.043541 -3.157307   1.088463  2.288644  1.359805 -1.064823   
4920      4462.0 -2.303350  1.759247  -0.359745  2.330243 -0.821628 -0.075788   
6108      6986.0 -4.397974  1.358367  -2.592844  2.679787 -1.128131 -1.706536   
6329      7519.0  1.234235  3.019740  -4.304597  4.732795  3.624201 -1.357746   
6331      7526.0  0.008430  4.137837  -6.240697  6.675732  0.768307 -3.353060   
6334      7535.0  0.026779  4.132464  -6.560600  6.348557  1.329666 -2.513479   
6336      7543.0  0.329594  3.712889  -5.775935  6.078266  1.667359 -2.420168   
6338      7551.0  0.316459  3.809076  -5.615159  6.047445  1.554026 -2.651353   
6427      7610.0  0.725646  2.300894  -5.329976  4.007683 -1.730411 -1.732193   
6446      7672.0  0.702710  2.426433  -5.234513  4.416661 -2.170806 -2.667554   
6472      7740.0  1.023874  2.001485  -4.769752  3.819195 -1.271754 -1.734662   
6529      7891.0 -1.585505  3.261585  -4.137422  2.357096 -1.405043 -1.879437   
6609      8090.0 -1.783229  3.402794  -3.822742  2.625368 -1.976415 -2.731689   
6641      8169.0  0.857321  4.093912  -7.423894  7.380245  0.973366 -2.730762   
6717      8408.0 -1.813280  4.917851  -5.926130  5.701500  1.204393 -3.035138   
6719      8415.0 -0.251471  4.313523  -6.891438  6.796797  0.616297 -2.966327   
6734      8451.0  0.314597  2.660670  -5.920037  4.522500 -2.315027 -2.278352   
6774      8528.0  0.447396  2.481954  -5.660814  4.455923 -2.443780 -2.185040   
6820      8614.0 -2.169929  3.639654  -4.508498  2.730668 -2.122693 -2.341017   
6870      8757.0 -1.863756  3.442644  -4.468260  2.805336 -2.118412 -2.332285   
6882      8808.0 -4.617217  1.695694  -3.114372  4.328199 -1.873257 -0.989908   
6899      8878.0 -2.661802  5.856393  -7.653616  6.379742 -0.060712 -3.131550   
6903      8886.0 -2.535852  5.793644  -7.618463  6.395830 -0.065210 -3.136372   
6971      9064.0 -3.499108  0.258555  -4.489558  4.853894 -6.974522  3.628382   
8296     11080.0 -2.125490  5.973556 -11.034727  9.007147 -1.689451 -2.854415   
8312     11092.0  0.378275  3.914797  -5.726872  6.094141  1.698875 -2.807314   
8335     11131.0 -1.426623  4.141986  -9.804103  6.666273 -4.749527 -2.073129   
8615     11629.0 -3.891192  7.098916 -11.426467  8.607557 -2.065706 -2.985288   
8617     11635.0  0.919137  4.199633  -7.535607  7.426940  1.118215 -2.886722   
...          ...       ...       ...        ...       ...       ...       ...   
251891  155548.0  1.878230  1.325630  -2.333469  4.233151  1.355184 -0.853508   
251904  155554.0 -1.040067  3.106703  -5.409027  3.109903 -0.887237 -2.497522   
252124  155662.0 -1.928613  4.601506  -7.124053  5.716088  1.026579 -3.189073   
252774  155965.0 -1.201398  4.864535  -8.328823  7.652399 -0.167445 -2.767695   
254344  156685.0 -0.129778  0.141547  -0.894702 -0.457662  0.810608 -0.504723   
254395  156710.0  0.202402  1.176270   0.346379  2.882138  1.407133 -0.504355   
255403  157207.0  1.170756  2.501038  -4.986159  5.374160  0.997798 -1.259004   
255556  157284.0 -0.242245  4.147186  -5.672349  6.493741  1.591168 -1.602523   
258403  158638.0 -5.976119 -7.196980  -5.388316  5.104799  4.676533 -5.566870   
261056  159844.0 -0.408111  3.132944  -3.098030  5.803893  0.890609 -0.501474   
261473  160034.0 -2.349340  1.512604  -2.647497  1.753792  0.406328 -2.188494   
261925  160243.0 -2.783865  1.596824  -2.084844  2.512986 -1.446749 -0.828496   
262560  160537.0  0.567539  3.309385  -6.631268  6.394574 -0.054172 -2.396535   
262826  160665.0 -0.417340  4.700055  -7.521767  7.671884  0.260821 -2.646693   
263080  160791.0  2.132386  0.705608  -3.530759  0.514779  1.527175 -1.716268   
263274  160870.0 -0.644278  5.002352  -8.252739  7.756915 -0.216267 -2.751496   
263324  160895.0 -0.848290  2.719882  -6.199070  3.044437 -3.301910 -1.992117   
263877  161154.0 -3.387601  3.977881  -6.97

In [4]:
import math


X_train, y_train, X_test, y_test = generate_train_test_timeseries(data)
print X_train.shape
print y_train.shape



(199365, 30)
(199365, 1)


In [5]:
X_test.head(10)

Time        V1        V2        V3        V4        V5        V6  \
199364  132929.0 -1.504565 -1.047164  2.658591 -0.246340  0.342667  0.182682   
199365  132929.0  2.152590 -0.900447 -1.092456 -0.994969 -0.613447 -0.760012   
199366  132929.0  1.811278  0.224393  0.542888  3.606222 -0.162910  1.171241   
199367  132929.0 -1.524832 -0.544095 -0.288824 -0.916791  3.524219 -1.830070   
199368  132930.0  0.099135  0.873164 -0.362487 -0.612234  0.747229 -0.629384   
199369  132930.0  2.005556 -0.146704 -1.019430  0.330239 -0.180449 -0.953319   
199370  132930.0 -0.972978  0.359825  0.979863 -0.864804  1.876989 -0.809730   
199371  132931.0 -0.040660  1.299237 -1.340674  0.651780  1.200997 -0.191688   
199372  132931.0  1.092328 -1.860651 -1.054998  1.470728  0.051875  2.633389   
199373  132931.0 -1.325669  0.625022  0.215274  0.039639  2.302044  4.676421   

              V7        V8        V9     ...            V20       V21  \
199364 -0.424257  0.300896  0.638538     ...       0.560674  0.371965   
199365 -0.530218 -0.222248 -0.214416     ...       0.060715 -0.281725   
199366 -0.874598  0.419449 -0.546470     ...      -0.198616  0.109290   
199367  1.375925 -0.814647 -0.648070     ...      -0.209666  0.272832   
199368  0.755890  0.126794 -0.051667     ...      -0.090654 -0.302759   
199369  0.053860 -0.165823  0.352282     ...      -0.241755 -0.235137   
199370  1.125462 -0.403589 -0.531036     ...       0.298142  0.245493   
199371  1.097722  0.244725 -1.303420     ...      -0.144117  0.385317   
199372 -0.620770  0.717955  1.483445     ...       0.368666  0.539129   
199373 -0.046687  1.290433 -0.109319     ...      -0.074782 -0.529958   

             V22       V23       V24       V25       V26       V27       V28  \
199364  0.798937 -0.048231 -0.437821  0.412388 -0.085327 -0.131134 -0.127378   
199365 -0.987236  0.358646 -0.782338 -0.480245 -0.647930 -0.023563 -0.044354   
199366  0.345703  0.365984  0.663253 -0.531272 -0.225013  0.032563 -0.022693   
199367  1.245119 -0.867245  0.838885  0.860487 -0.081074 -0.252743 -0.377957   
199368 -0.840999  0.115856  0.613080 -0.528392  0.092546  0.207960  0.071553   
199369 -0.613122  0.342269  0.063677 -0.359509  0.174021 -0.078440 -0.069642   
199370  0.713429 -0.554851  0.543635  1.176300 -0.036967 -0.183880 -0.160094   
199371  0.984711  0.004701  0.218244 -0.767317 -0.550411  0.141207  0.204165   
199372  1.205393 -0.344476 -0.902377 -0.009404 -0.244045  0.038282  0.001911   
199373 -1.405320 -0.245663  0.652001  0.311430 -0.831220 -0.323458 -0.310960   

        norm_Amount  
199364     0.120864  
199365    -0.129536  
199366    -0.350071  
199367    -0.229689  
199368    -0.346113  
199369    -0.331760  
199370    -0.280424  
199371    -0.201702  
199372     1.158047  
199373    -0.069525  

[10 rows x 30 columns]

In [6]:
print X_train.shape
print y_train.shape
print X_test.shape
print y_test.shape

(199365, 30)
(199365, 1)
(85443, 30)
(85443, 1)


In [7]:
def reshape_to_batches(a, batch_size):
    # pad with zeros if the length is not divisible by the batch_size
    batch_num = np.ceil((float)(a.shape[0]) / batch_size)
    modulo = batch_num * batch_size - a.shape[0]
    if modulo != 0:
        pad = np.zeros((int(modulo), a.shape[1]))
        a = np.vstack((a, pad))
    return np.array(np.split(a, batch_num))

In [8]:
X_train_batch = reshape_to_batches(X_train, 100)

In [9]:
X_train_batch.shape

(1994, 100, 30)

In [10]:
y_test.shape

(85443, 1)

In [11]:
y_test = keras.utils.to_categorical(y_test)
y_train = keras.utils.to_categorical(y_train)

In [136]:
y_test.shape

(85443, 2)

In [12]:
y_train_batch = reshape_to_batches(y_train, 100)
y_test_batch = reshape_to_batches(y_test, 100)
X_test_batch = reshape_to_batches(X_test, 100)

In [13]:
print X_train_batch.shape
print X_test_batch.shape
print y_train_batch.shape
print y_test_batch.shape

(1994, 100, 30)
(855, 100, 30)
(1994, 100, 2)
(855, 100, 2)


In [23]:
#import all dependencies
from keras.layers import Input, Dense, Conv1D
from keras.models import Model

In [24]:
inputs = Input(shape=(100, 30)) # This returns a tensor

In [25]:
# a layer instance is callable on a tensor, and returns a tensor
conv1 = Conv1D(32, (5), # 32 filters with a window of width 5
strides=1, # think autoregression
padding='causal', # forward in time
dilation_rate=1, # ignore this and everything that follows are default parameters
activation='relu',
use_bias=True,
kernel_initializer='glorot_uniform',
bias_initializer='zeros',
kernel_regularizer=None, # no regularisation for the moment
bias_regularizer=None,
activity_regularizer=None,
kernel_constraint=None,
bias_constraint=None)(inputs) # syntax to chain layers: Layer(...)(PreviousLayer)

In [26]:
fc1 = Dense(64, activation='relu')(conv1)

In [27]:
predictions = Dense(2, activation='softmax')(fc1)

In [28]:
model = Model(inputs=inputs,
outputs=predictions)
model.compile(optimizer='rmsprop',
loss='categorical_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(X_train_batch, y_train_batch, epochs=30)

Epoch 1/30
1994/1994 [==============================] - 1s 478us/step - loss: 2.1534 - acc: 0.8664
Epoch 2/30
1994/1994 [==============================] - 1s 335us/step - loss: 0.0311 - acc: 0.9981
Epoch 3/30
1994/1994 [==============================] - 1s 336us/step - loss: 0.0311 - acc: 0.9981
Epoch 4/30
1994/1994 [==============================] - 1s 340us/step - loss: 0.0311 - acc: 0.9981
Epoch 5/30
1994/1994 [==============================] - 1s 341us/step - loss: 0.0310 - acc: 0.9981
Epoch 6/30
1994/1994 [==============================] - 1s 344us/step - loss: 0.0310 - acc: 0.9981
Epoch 7/30
1994/1994 [==============================] - 1s 340us/step - loss: 0.0310 - acc: 0.9981
Epoch 8/30
1994/1994 [==============================] - 1s 369us/step - loss: 0.0310 - acc: 0.9981
Epoch 9/30
1994/1994 [==============================] - 1s 367us/step - loss: 0.0310 - acc: 0.9981
Epoch 10/30
1994/1994 [==============================] - 1s 345us/step - loss: 0.0310 - acc: 0.9981
Epoch 11/

In [30]:
y_pred = model.predict(X_test_batch)

In [31]:
y_pred_3d = y_pred

# a function to reshape batches into the original shape
def _3d_to_2d(arr):
    return arr.reshape(arr.shape[0] * arr.shape[1], arr.shape[2])

In [32]:
from sklearn.metrics import confusion_matrix
cutt_off_tr = 0.5
y_pred[np.where(y_pred>=cutt_off_tr)] = 1
y_pred[np.where(y_pred<cutt_off_tr)]  = 0

y_pred_2d = _3d_to_2d(y_pred)[:,1]
y_test_2d = _3d_to_2d(y_test_batch)[:,1]

print(confusion_matrix(
_3d_to_2d(y_test_batch)[:, 1],
_3d_to_2d(y_pred)[:, 1]))

prfs = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[1])
prfs0 = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[0])
print prfs
print "\n"
print prfs0

[[85392     0]
 [  108     0]]
(array([ 0.]), array([ 0.]), array([ 0.]), array([108]))


(array([ 0.99873684]), array([ 1.]), array([ 0.99936802]), array([85392]))


In [14]:
conv1d = Conv1D(32, (5), input_shape=(100, 30), strides=1,padding='causal')

In [15]:
seed(2017)
conv = Sequential()
conv.add(conv1d)
conv.add(Dense(64, activation='relu'))
conv.add(Dense(2, activation='softmax'))

In [17]:
sgd = SGD(lr = 0.1, momentum = 0.9, decay = 0, nesterov = False)
conv.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])
conv.fit(X_train_batch, y_train_batch, epochs = 30, verbose = 50)

Epoch 1/30
Epoch 2/30
Epoch 3/30
Epoch 4/30
Epoch 5/30
Epoch 6/30
Epoch 7/30
Epoch 8/30
Epoch 9/30
Epoch 10/30
Epoch 11/30
Epoch 12/30
Epoch 13/30
Epoch 14/30
Epoch 15/30
Epoch 16/30
Epoch 17/30
Epoch 18/30
Epoch 19/30
Epoch 20/30
Epoch 21/30
Epoch 22/30
Epoch 23/30
Epoch 24/30
Epoch 25/30
Epoch 26/30
Epoch 27/30
Epoch 28/30
Epoch 29/30
Epoch 30/30


In [18]:
y_pred = conv.predict(X_test_batch)

In [19]:
y_pred_3d = y_pred

# a function to reshape batches into the original shape
def _3d_to_2d(arr):
    return arr.reshape(arr.shape[0] * arr.shape[1], arr.shape[2])



In [20]:
print y_pred_2d.shape
print y_test_2d.shape

NameError: name 'y_pred_2d' is not defined

In [21]:
from sklearn.metrics import confusion_matrix
cutt_off_tr = 0.5
y_pred[np.where(y_pred>=cutt_off_tr)] = 1
y_pred[np.where(y_pred<cutt_off_tr)]  = 0

y_pred_2d = _3d_to_2d(y_pred)[:,1]
y_test_2d = _3d_to_2d(y_test_batch)[:,1]

print(confusion_matrix(
_3d_to_2d(y_test_batch)[:, 1],
_3d_to_2d(y_pred)[:, 1]))

prfs = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[1])
prfs0 = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[0])
print prfs
print "\n"
print prfs0

[[85392     0]
 [  108     0]]
(array([ 0.]), array([ 0.]), array([ 0.]), array([108]))


(array([ 0.99873684]), array([ 1.]), array([ 0.99936802]), array([85392]))


/Users/HarryG1/Documents/University/Year_3/DeepLearning-CreditCardFraud/devEnv/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
y_pred_2d

In [ ]:
from sklearn.metrics import roc_curve, auc, roc_auc_score

print(roc_auc_score(y_test_2d[:, 1],
y_pred_2d[:, 1]))

In [22]:
from collections import Counter
Counter(y_pred_2d)


Counter({0.0: 85500})