In [623]:
from numpy.random import seed
import pandas as pd
import numpy as np
from sklearn.preprocessing import minmax_scale
# from keras_diagram import ascii
from keras.layers.convolutional import Conv2D, MaxPooling2D, Conv1D, MaxPooling1D
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support
import keras
import math
data_raw = pd.read_csv("creditcard.csv")



In [624]:
# Assign variables x and y corresponding to row data and it's class value
X = data_raw.loc[:, data.columns != 'Class']
y = data_raw.loc[:, data.columns == 'Class']

In [625]:
int(X.shape[0]*0.7)

199364

In [626]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

def generate_train_test_timeseries(data, test_ratio=0.3):
#     cutoff = math.floor(X.shape[0] *cuttoff_percent) 
#     print cutoff
    total_samples = data.shape[0]
    # splitting index
    cutoff = int(total_samples * (1 - test_ratio))

    
    data.sort_values('Time', inplace=True)
    
    X_train = data.loc[0:cutoff, data.columns != 'Class']
    y_train = data.loc[0:cutoff, data.columns == 'Class']
    X_test = data.loc[cutoff:, data.columns != 'Class']
    y_test = data.loc[cutoff:, data.columns == 'Class']
    
    pipeline = Pipeline([
        ('scaling', StandardScaler()),
    ])
    preprocessor = pipeline.fit(X_train)
    X_train_prp = preprocessor.transform(X_train)
    
#     preprocessor = pipeline.fit(X_test)
    X_test_prp = preprocessor.transform(X_test)
    
#     # Normalise ALL columns - X_Train
#     from sklearn.preprocessing import StandardScaler
#     norm_cols = StandardScaler().fit_transform(X_train)
#     X_train = pd.DataFrame(norm_cols)
    
#     # Normalise ALL columns - X_Test
#     from sklearn.preprocessing import StandardScaler
#     norm_cols = StandardScaler().fit_transform(X_test)
#     X_test = pd.DataFrame(norm_cols)
    
    
    return X_train_prp, y_train, X_test_prp, y_test
    
########################################################################

# X_res, y_res, X_test, y_test = generate_train_test_sample(X, y)

# print X_res.shape, type(X_res)
# print y_res.shape

# X_train = X_res.reshape(X_res.shape[0], 29, 1)
# Y_train = y_res.reshape(y_res.shape[0], 1)
# X_test = X_test.values.reshape(X_test.values.shape[0], 29, 1)
# Y_test = y_test.values.reshape(y_test.values.shape[0], 1)

# Y_test = keras.utils.to_categorical(Y_test)
# Y_train = keras.utils.to_categorical(Y_train)
# print Y_test.shape
# print Y_train.shape




In [627]:
X_train, y_train, X_test, y_test = generate_train_test_timeseries(data_raw)

# observe the mean and the variance of the tranformed data set for each fature
checker = lambda x: [np.mean(x), np.var(x)]
pd.DataFrame(X_train).apply(checker)

0      [2.37221801681e-16, 1.0]
1      [1.65370967518e-17, 1.0]
2     [-3.13634593569e-18, 1.0]
3     [-4.79005561087e-17, 1.0]
4      [1.71073414674e-18, 1.0]
5       [2.1669299192e-17, 1.0]
6      [4.27683536685e-18, 1.0]
7     [-2.28097886232e-18, 1.0]
8     [-1.42561178895e-18, 1.0]
9      [2.62312569167e-17, 1.0]
10    [-4.27683536685e-18, 1.0]
11     [5.93054504203e-17, 1.0]
12     [3.19337040725e-17, 1.0]
13     [1.73924638252e-17, 1.0]
14     [-2.8512235779e-17, 1.0]
15     [1.25453837428e-17, 1.0]
16    [-1.99585650453e-18, 1.0]
17     [1.14048943116e-18, 1.0]
18     [-1.0834649596e-17, 1.0]
19     [1.26166643322e-17, 1.0]
20    [-1.14048943116e-18, 1.0]
21    [-3.99171300906e-18, 1.0]
22     [3.42146829348e-17, 1.0]
23     [5.98756951359e-18, 1.0]
24     [2.49482063066e-17, 1.0]
25    [-6.95698553008e-17, 1.0]
26    [-9.26647662818e-18, 1.0]
27    [-8.26854837591e-18, 1.0]
28    [-9.12391544928e-18, 1.0]
29      [4.2055547774e-18, 1.0]
dtype: object

In [628]:
pd.DataFrame(X_test).apply(checker)

0         [2.3542902492, 0.101162296229]
1        [0.185810693741, 1.21860638875]
2     [-0.00771279211375, 1.12244913422]
3      [-0.738688825683, 0.942061396417]
4        [-0.17983654767, 1.05712304367]
5        [0.274557741571, 1.03950113753]
6       [-0.116894042519, 1.09946461167]
7        [0.138438463223, 1.09153568284]
8     [-0.0472197909783, 0.914012666523]
9     [-0.0258953529381, 0.785262337184]
10     [0.0342903908915, 0.975745745013]
11     [-0.403980218415, 0.757623382476]
12      [0.213213479705, 0.415170985072]
13      [-0.12035072016, 0.757388461736]
14      [-0.174103500009, 0.88856693772]
15         [-0.297065407, 0.73485281857]
16     [0.0223151840834, 0.927390725625]
17    [-0.0997550510562, 0.690374296232]
18      [0.143057666019, 0.974411197554]
19     [0.0543747049487, 0.956058532395]
20     [-0.0884062249473, 1.19046798698]
21     [0.0662583401281, 0.963964937722]
22         [0.231040162274, 1.302401999]
23      [0.0846970360626, 1.14626364524]
24     [-0.02366

In [629]:
X_train.shape

(199365, 30)

In [630]:
data_raw[data_raw['Class']==1]

Time        V1        V2         V3        V4        V5        V6  \
541        406.0 -2.312227  1.951992  -1.609851  3.997906 -0.522188 -1.426545   
623        472.0 -3.043541 -3.157307   1.088463  2.288644  1.359805 -1.064823   
4920      4462.0 -2.303350  1.759247  -0.359745  2.330243 -0.821628 -0.075788   
6108      6986.0 -4.397974  1.358367  -2.592844  2.679787 -1.128131 -1.706536   
6329      7519.0  1.234235  3.019740  -4.304597  4.732795  3.624201 -1.357746   
6331      7526.0  0.008430  4.137837  -6.240697  6.675732  0.768307 -3.353060   
6334      7535.0  0.026779  4.132464  -6.560600  6.348557  1.329666 -2.513479   
6336      7543.0  0.329594  3.712889  -5.775935  6.078266  1.667359 -2.420168   
6338      7551.0  0.316459  3.809076  -5.615159  6.047445  1.554026 -2.651353   
6427      7610.0  0.725646  2.300894  -5.329976  4.007683 -1.730411 -1.732193   
6446      7672.0  0.702710  2.426433  -5.234513  4.416661 -2.170806 -2.667554   
6472      7740.0  1.023874  2.001485  -4.769752  3.819195 -1.271754 -1.734662   
6529      7891.0 -1.585505  3.261585  -4.137422  2.357096 -1.405043 -1.879437   
6609      8090.0 -1.783229  3.402794  -3.822742  2.625368 -1.976415 -2.731689   
6641      8169.0  0.857321  4.093912  -7.423894  7.380245  0.973366 -2.730762   
6717      8408.0 -1.813280  4.917851  -5.926130  5.701500  1.204393 -3.035138   
6719      8415.0 -0.251471  4.313523  -6.891438  6.796797  0.616297 -2.966327   
6734      8451.0  0.314597  2.660670  -5.920037  4.522500 -2.315027 -2.278352   
6774      8528.0  0.447396  2.481954  -5.660814  4.455923 -2.443780 -2.185040   
6820      8614.0 -2.169929  3.639654  -4.508498  2.730668 -2.122693 -2.341017   
6870      8757.0 -1.863756  3.442644  -4.468260  2.805336 -2.118412 -2.332285   
6882      8808.0 -4.617217  1.695694  -3.114372  4.328199 -1.873257 -0.989908   
6899      8878.0 -2.661802  5.856393  -7.653616  6.379742 -0.060712 -3.131550   
6903      8886.0 -2.535852  5.793644  -7.618463  6.395830 -0.065210 -3.136372   
6971      9064.0 -3.499108  0.258555  -4.489558  4.853894 -6.974522  3.628382   
8296     11080.0 -2.125490  5.973556 -11.034727  9.007147 -1.689451 -2.854415   
8312     11092.0  0.378275  3.914797  -5.726872  6.094141  1.698875 -2.807314   
8335     11131.0 -1.426623  4.141986  -9.804103  6.666273 -4.749527 -2.073129   
8615     11629.0 -3.891192  7.098916 -11.426467  8.607557 -2.065706 -2.985288   
8617     11635.0  0.919137  4.199633  -7.535607  7.426940  1.118215 -2.886722   
...          ...       ...       ...        ...       ...       ...       ...   
251891  155548.0  1.878230  1.325630  -2.333469  4.233151  1.355184 -0.853508   
251904  155554.0 -1.040067  3.106703  -5.409027  3.109903 -0.887237 -2.497522   
252124  155662.0 -1.928613  4.601506  -7.124053  5.716088  1.026579 -3.189073   
252774  155965.0 -1.201398  4.864535  -8.328823  7.652399 -0.167445 -2.767695   
254344  156685.0 -0.129778  0.141547  -0.894702 -0.457662  0.810608 -0.504723   
254395  156710.0  0.202402  1.176270   0.346379  2.882138  1.407133 -0.504355   
255403  157207.0  1.170756  2.501038  -4.986159  5.374160  0.997798 -1.259004   
255556  157284.0 -0.242245  4.147186  -5.672349  6.493741  1.591168 -1.602523   
258403  158638.0 -5.976119 -7.196980  -5.388316  5.104799  4.676533 -5.566870   
261056  159844.0 -0.408111  3.132944  -3.098030  5.803893  0.890609 -0.501474   
261473  160034.0 -2.349340  1.512604  -2.647497  1.753792  0.406328 -2.188494   
261925  160243.0 -2.783865  1.596824  -2.084844  2.512986 -1.446749 -0.828496   
262560  160537.0  0.567539  3.309385  -6.631268  6.394574 -0.054172 -2.396535   
262826  160665.0 -0.417340  4.700055  -7.521767  7.671884  0.260821 -2.646693   
263080  160791.0  2.132386  0.705608  -3.530759  0.514779  1.527175 -1.716268   
263274  160870.0 -0.644278  5.002352  -8.252739  7.756915 -0.216267 -2.751496   
263324  160895.0 -0.848290  2.719882  -6.199070  3.044437 -3.301910 -1.992117   
263877  161154.0 -3.387601  3.977881  -6.97

In [631]:
import math


X_train, y_train, X_test, y_test = generate_train_test_timeseries(data_raw)
print X_train.shape
print y_train.shape



(199365, 30)
(199365, 1)


In [632]:
X_train

array([[-2.04169282, -0.66333395, -0.04718907, ...,  0.33491107,
        -0.07318358,  0.24044257],
       [-2.04169282,  0.68601299,  0.16179919, ..., -0.02682455,
         0.04081383, -0.34985017],
       [-2.04166384, -0.66256555, -0.82866747, ..., -0.14449956,
        -0.19649   ,  1.16061305],
       ..., 
       [ 1.81094662, -0.67591045, -3.47526897, ..., -1.05173088,
         0.61955003,  6.65150461],
       [ 1.81094662, -0.78522762,  0.72888384, ..., -0.28086169,
        -0.40880546, -0.19879179],
       [ 1.81097561, -0.73988366, -0.64800196, ..., -0.33681341,
        -0.41196738,  0.11573906]])

In [633]:
print X_train.shape
print y_train.shape
print X_test.shape
print y_test.shape

(199365, 30)
(199365, 1)
(85443, 30)
(85443, 1)


In [634]:
#com add your code here
import seaborn as sns
#hide
sns.distplot(X_train[:, 0])
#/hide

In [635]:
def reshape_to_batches(a, batch_size):
    # pad with zeros if the length is not divisible by the batch_size
    batch_num = np.ceil((float)(a.shape[0]) / batch_size)
    modulo = batch_num * batch_size - a.shape[0]
    if modulo != 0:
        pad = np.zeros((int(modulo), a.shape[1]))
        a = np.vstack((a, pad))
    return np.array(np.split(a, batch_num))

In [636]:
X_train_batch = reshape_to_batches(X_train, 100)

In [637]:
X_train_batch.shape

(1994, 100, 30)

In [638]:
y_test.shape

(85443, 1)

In [639]:
y_test = keras.utils.to_categorical(y_test)
y_train = keras.utils.to_categorical(y_train)

In [640]:
y_test.shape

(85443, 2)

In [641]:
y_test

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [642]:
y_train_batch = reshape_to_batches(y_train, 100)
y_test_batch = reshape_to_batches(y_test, 100)
X_test_batch = reshape_to_batches(X_test, 100)

In [643]:
print X_train_batch.shape
print X_test_batch.shape
print y_train_batch.shape
print y_test_batch.shape

(1994, 100, 30)
(855, 100, 30)
(1994, 100, 2)
(855, 100, 2)


In [644]:
#import all dependencies
from keras.layers import Input, Dense, Conv1D
from keras.models import Model

seed(2018)

In [645]:
inputs = Input(shape=(100, 30)) # This returns a tensor

In [646]:
# a layer instance is callable on a tensor, and returns a tensor
conv1 = Conv1D(32, (5), # 32 filters with a window of width 5
strides=1, # think autoregression
padding='causal', # forward in time
dilation_rate=1, # ignore this and everything that follows are default parameters
activation='relu',
use_bias=True,
kernel_initializer='glorot_uniform',
bias_initializer='zeros',
kernel_regularizer=None, # no regularisation for the moment
bias_regularizer=None,
activity_regularizer=None,
kernel_constraint=None,
bias_constraint=None)(inputs) # syntax to chain layers: Layer(...)(PreviousLayer)

In [647]:
fc1 = Dense(64, activation='relu')(conv1)

In [648]:
predictions = Dense(2, activation='softmax')(fc1)

In [649]:
model = Model(inputs=inputs,
outputs=predictions)
model.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [650]:
X_train_batch

array([[[-2.04169282, -0.66333395, -0.04718907, ...,  0.33491107,
         -0.07318358,  0.24044257],
        [-2.04169282,  0.68601299,  0.16179919, ..., -0.02682455,
          0.04081383, -0.34985017],
        [-2.04166384, -0.66256555, -0.82866747, ..., -0.14449956,
         -0.19649   ,  1.16061305],
        ..., 
        [-2.03975097, -0.28980201,  0.09648455, ...,  0.02449283,
         -0.16375542, -0.2809097 ],
        [-2.03975097, -0.73464971,  0.51393854, ..., -0.80972917,
         -1.09194432, -0.24704209],
        [-2.03972199,  0.70776792,  0.11450719, ..., -0.08812375,
          0.06077998, -0.29641728]],

       [[-2.03972199,  0.66754796,  0.02063557, ..., -0.07207959,
          0.00727618, -0.34985017],
        [-2.03972199, -0.35154157,  0.29586326, ...,  0.14564766,
          0.42146265, -0.27082575],
        [-2.039693  ,  0.21359801,  1.31890862, ...,  0.63331734,
         -0.77807727, -0.35752361],
        ..., 
        [-2.03792505,  0.77137675, -0.43079279, ...,

In [651]:
model.fit(X_train_batch, y_train_batch, epochs=30)

Epoch 1/30
1994/1994 [==============================] - 2s 763us/step - loss: 0.0973 - acc: 0.9869
Epoch 2/30
1994/1994 [==============================] - 1s 273us/step - loss: 0.0067 - acc: 0.9987
Epoch 3/30
1994/1994 [==============================] - 1s 262us/step - loss: 0.0040 - acc: 0.9992
Epoch 4/30
1994/1994 [==============================] - 1s 263us/step - loss: 0.0033 - acc: 0.9993
Epoch 5/30
1994/1994 [==============================] - 1s 262us/step - loss: 0.0029 - acc: 0.9994
Epoch 6/30
1994/1994 [==============================] - 1s 265us/step - loss: 0.0025 - acc: 0.9994
Epoch 7/30
1994/1994 [==============================] - 1s 261us/step - loss: 0.0022 - acc: 0.9994
Epoch 8/30
1994/1994 [==============================] - 1s 265us/step - loss: 0.0020 - acc: 0.9995
Epoch 9/30
1994/1994 [==============================] - 1s 266us/step - loss: 0.0017 - acc: 0.9995
Epoch 10/30
1994/1994 [==============================] - 1s 274us/step - loss: 0.0015 - acc: 0.9995
Epoch 11/

In [652]:
y_pred = model.predict(X_test_batch)

In [653]:
y_pred_3d = y_pred

# store the raw predictions we will need them in a bit
y_hat = np.copy(y_pred)

# a function to reshape batches into the original shape
def _3d_to_2d(arr):
    return arr.reshape(arr.shape[0] * arr.shape[1], arr.shape[2])

In [654]:
from sklearn.metrics import confusion_matrix, classification_report
cutt_off_tr = 0.5
y_pred[np.where(y_pred>=cutt_off_tr)] = 1
y_pred[np.where(y_pred<cutt_off_tr)]  = 0

y_pred_2d = _3d_to_2d(y_pred)[:,1]
y_test_2d = _3d_to_2d(y_test_batch)[:,1]

print(confusion_matrix(
_3d_to_2d(y_test_batch)[:, 1],
_3d_to_2d(y_pred)[:, 1]))

prfs = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[1])
prfs0 = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[0])
print prfs
print "\n"
print prfs0

[[85389     3]
 [   44    64]]
(array([ 0.95522388]), array([ 0.59259259]), array([ 0.73142857]), array([108]))


(array([ 0.99948498]), array([ 0.99996487]), array([ 0.99972486]), array([85392]))


In [655]:
print(classification_report(
y_test_2d,
y_pred_2d,
target_names = ["Genuine", "Fraud"],
digits = 5))

             precision    recall  f1-score   support

    Genuine    0.99948   0.99996   0.99972     85392
      Fraud    0.95522   0.59259   0.73143       108

avg / total    0.99943   0.99945   0.99939     85500



In [656]:
from sklearn.metrics import roc_curve, auc, roc_auc_score

# short way
print(roc_auc_score(y_test_2d, _3d_to_2d(y_hat)[:, 1]))

0.943559039705


In [657]:
X_train_batch

array([[[-2.04169282, -0.66333395, -0.04718907, ...,  0.33491107,
         -0.07318358,  0.24044257],
        [-2.04169282,  0.68601299,  0.16179919, ..., -0.02682455,
          0.04081383, -0.34985017],
        [-2.04166384, -0.66256555, -0.82866747, ..., -0.14449956,
         -0.19649   ,  1.16061305],
        ..., 
        [-2.03975097, -0.28980201,  0.09648455, ...,  0.02449283,
         -0.16375542, -0.2809097 ],
        [-2.03975097, -0.73464971,  0.51393854, ..., -0.80972917,
         -1.09194432, -0.24704209],
        [-2.03972199,  0.70776792,  0.11450719, ..., -0.08812375,
          0.06077998, -0.29641728]],

       [[-2.03972199,  0.66754796,  0.02063557, ..., -0.07207959,
          0.00727618, -0.34985017],
        [-2.03972199, -0.35154157,  0.29586326, ...,  0.14564766,
          0.42146265, -0.27082575],
        [-2.039693  ,  0.21359801,  1.31890862, ...,  0.63331734,
         -0.77807727, -0.35752361],
        ..., 
        [-2.03792505,  0.77137675, -0.43079279, ...,

In [680]:
len(y_hat[np.where(y_hat >= cutt_off_tr)])

85500

In [679]:
len(np.where(y_pred[1] == 1)[0])

100

In [682]:
_3d_to_2d(y_pred)[:, 1]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [689]:
np.where(y_hat[:,:,1]>0.5)

(array([  5,  17,  39,  39,  43,  47,  51,  92, 132, 137, 152, 166, 213,
        227, 240, 242, 242, 242, 274, 275, 303, 305, 307, 311, 352, 352,
        352, 353, 362, 362, 377, 378, 388, 401, 401, 420, 440, 441, 443,
        443, 444, 446, 449, 483, 486, 489, 498, 504, 505, 513, 521, 525,
        525, 527, 534, 560, 561, 621, 631, 634, 634, 639, 639, 645, 690,
        775, 804]),
 array([32, 36, 62, 64, 36,  0, 39, 87, 80, 54, 98, 20, 61, 69,  2,  6, 14,
        54, 50, 13, 48, 89, 13, 10, 10, 68, 69, 41, 52, 80, 43, 29, 58, 35,
        37, 81, 29, 83, 35, 85, 84, 40, 67,  9, 31, 32,  3, 64, 99, 97, 13,
         2, 40, 60, 10, 39, 92,  9, 96, 62, 79, 10, 60, 13, 10,  0, 99]))

In [692]:
y_hat[:][5]

array([[  1.00000000e+00,   2.19847505e-18],
       [  1.00000000e+00,   4.80529846e-19],
       [  1.00000000e+00,   7.84376979e-29],
       [  1.00000000e+00,   1.22740433e-32],
       [  1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   4.90221346e-31],
       [  1.00000000e+00,   7.77231147e-30],
       [  1.00000000e+00,   5.72898769e-26],
       [  1.00000000e+00,   6.86874995e-24],
       [  1.00000000e+00,   1.44047465e-27],
       [  1.00000000e+00,   2.54878514e-35],
       [  1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   2.80295370e-38],
       [  1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00],
       [  1.00000000e+00,   1.26569988e-32],
       [  1.00000000e+00,   6.21898321e-37],
       [  1.00000000e+00,   6.10997121e-21],
       [  1.00000000e+00,   7.72909163e-21],
       [  1.00000000e+00,   8.38820638e-31],
       [  1.00000000e+00,   9.73068978e-28],
       [  

In [658]:
conv1d = Conv1D(32, (5), input_shape=(100, 30), strides=1,padding='causal')

In [659]:
seed(2017)
conv = Sequential()
conv.add(conv1d)
conv.add(Dense(64, activation='relu'))
conv.add(Dense(2, activation='softmax'))

In [660]:
sgd = SGD(lr = 0.1, momentum = 0.9, decay = 0, nesterov = False)
conv.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])
conv.fit(X_train_batch, y_train_batch, epochs = 30, verbose = 50)

Epoch 1/30
Epoch 2/30
Epoch 3/30
Epoch 4/30
Epoch 5/30
Epoch 6/30
Epoch 7/30
Epoch 8/30
Epoch 9/30
Epoch 10/30
Epoch 11/30
Epoch 12/30
Epoch 13/30
Epoch 14/30
Epoch 15/30
Epoch 16/30
Epoch 17/30
Epoch 18/30
Epoch 19/30
Epoch 20/30
Epoch 21/30
Epoch 22/30
Epoch 23/30
Epoch 24/30
Epoch 25/30
Epoch 26/30
Epoch 27/30
Epoch 28/30
Epoch 29/30
Epoch 30/30


In [661]:
y_pred = conv.predict(X_test_batch)

In [662]:
y_pred_3d = y_pred

# a function to reshape batches into the original shape
def _3d_to_2d(arr):
    return arr.reshape(arr.shape[0] * arr.shape[1], arr.shape[2])



In [663]:
print y_pred_2d.shape
print y_test_2d.shape

(85500,)
(85500,)


In [664]:
from sklearn.metrics import confusion_matrix
cutt_off_tr = 0.5
y_pred[np.where(y_pred>=cutt_off_tr)] = 1
y_pred[np.where(y_pred<cutt_off_tr)]  = 0

y_pred_2d = _3d_to_2d(y_pred)[:,1]
y_test_2d = _3d_to_2d(y_test_batch)[:,1]

print(confusion_matrix(
_3d_to_2d(y_test_batch)[:, 1],
_3d_to_2d(y_pred)[:, 1]))

prfs = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[1])
prfs0 = precision_recall_fscore_support(y_test_2d, y_pred_2d, labels=[0])
print prfs
print "\n"
print prfs0

[[85384     8]
 [   43    65]]
(array([ 0.89041096]), array([ 0.60185185]), array([ 0.71823204]), array([108]))


(array([ 0.99949665]), array([ 0.99990631]), array([ 0.99970144]), array([85392]))


In [665]:
y_pred_2d

array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32)

In [666]:
from sklearn.metrics import roc_curve, auc, roc_auc_score

print(roc_auc_score(y_test_2d[:, 1],
y_pred_2d[:, 1]))

IndexError: too many indices for array

In [ ]:
from collections import Counter
Counter(y_pred_2d)
